### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by ycanerol** [ganguli-lab/nems#4]
Trying to install on a fresh conda environment on Ubuntu 16.04, Python 3.7, I ran into the following exceptions after following the installation steps and trying to `import nems`.
1) No module named `h5py`. `pip install h5py` solves it.
2) No module named `sklearn`. `pip install sklearn` solves it.
3) No module named `proxalgs`. `pip install proxalgs` solves it.
3.1) No module named `toolz` (while installing proxalgs). `pip install toolz` solves it.
4) No module named `tqdm`. `pip install tqdm` solves it.
5) No module named `matplotlib`. `pip install matplotlib` solves it.
5.1) ImportError: Failed to import any qt binding. `pip install pyqt5` solves this. This is more related to how matplotlib is installed, I guess.
6) No module named `jetpack`. Trying to install using pip, an [unrelated package](https://pypi.org/project/jetpack/) comes up. Clone and install from [nirum/jetpack](https://github.com/nirum/jetpack).
6.1) No module named `moviepy`. `pip install moviepy` solves it. 
6.2) No module named `requests`. `pip install requests` solves it. Perhaps moviepy and requests need to be added to jetpack requirements?
7) No module named `pyret`. Clone and install from [baccuslab/pyret](https://github.com/baccuslab/pyret).
After all of these steps, `import nems` is successful if the working directory is set to where jetpack was cloned into.
Otherwise this error is produced.
ImportError: cannot import name 'img' from 'jetpack'.

Also upon nems import, `need to install descent: github.com/nirum/descent` message is emitted but no exception is thrown.

Most of the import errors could be resolved by adding the missing packages to the respective requirements.txt files for pip to automatically install them.
For nems: h5py, sklearn, proxalgs, tqdm, matplotlib, pyqt5 (?)
For proxalgs: toolz
For jetpack: moviepy, requests

pyret and jetpack need to be installed manually most probably.

**Comment by nirum** [comment]
Ah shoot, thanks for catching this. I can get rid of the `jetpack` and `moviepy` dependencies. I added the other dependencies to the `requirements.txt` file. Will get rid of the other dependencies and comment here once I do.

**Comment by nirum** [comment]
OK I believe these should be fixed now!
